version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pln_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: viera
      POSTGRES_DB: pltd_logsheet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pln_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      WACB_BASE_URL: "http://wacb.nusadaya.net/api"
      JWT_SECRET: "pln-nusa-daya-wacb-super-secret-jwt-key-2026"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "viera"
      DB_NAME: "pltd_logsheet"
      DB_SSLMODE: "disable"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pln_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080/api"
    depends_on:
      - backend

volumes:
  pgdata:
